### ISSUE TITLE
Interoperability with PyVista

### ISSUE THREAD

**Issue by banesullivan** [cgre-aachen/gempy#156]
I've been poking around some of the 3D viz code you all have here - it's really awesome work! 

I'm curious what your (`gempy` developers') thoughts would be on merging some of the 3D viz code here into [`vtki`](http://docs.vtki.org) and having `gempy` call back to `vtki` for all its 3D visualization needs?

Check out recent development for `vtki` - a LOT has changed in the past few months and I think `gempy` would be an awesome place for us to collaborate and showcase how `vtki` can be used as a supporting module for 3D viz.

- [Repository](https://github.com/vtkiorg/vtki)
- [Examples](http://docs.pyvista.org/examples/index.html)

This might help address: #149, #42, #36, and #32

I also saw that you all have a way to export scenes for Steno3D? Perhaps https://github.com/vtkiorg/vtki/issues/163 would also be of interest for this

**Comment by Leguark** [comment]
Hey Bane! Great to hear about you again. Actually I did not know that you were also the developer of vtki! I thought that PVGeo was getting you entertained enough :D 

As I told you in D.C I cannot agree more that we need a decoupled, compatible library for visualization of geomodeling data. I have already use vtki for couple of personal plots. I am still annoyed of the fact that we coded the vtk module just some months before your awesome library. 

Are you going next month to the transform "unconference" in Paris? I think getting ivtk with PVgeo as the main library of visualization for the software underground community would be a great beginning (if you cannot make it, I will lobby for it). And also I will suggest a sprint to merge gempy into ivtk.

I hope we can move this story soon!

**Comment by banesullivan** [comment]
> we need a decoupled, compatible library for visualization of geomodeling data. I have already use vtki for couple of personal plots. I am still annoyed of the fact that we coded the vtk module just some months before your awesome library.

Our goal with `vtki` is to create exactly that: *a decoupled, compatible library for visualization of **insert data type***, so right on point! Talking to you and few others at AGU inspired me to take on adding features to `vtki` - ended up developing a lot in hopes of attracting more users to PVGeo since I frequently heard people want 3D viz in Python, not ParaView - ~5 months later, here we are!

> Are you going next month to the transform "unconference" in Paris? I think getting vtki with PVGeo as the main library of visualization for the software underground community would be a great beginning (if you cannot make it, I will lobby for it). 

Unfortunately, I am not going 😞. I'd greatly appreciate any lobbying you can do for PVGeo+`vtki` being a go-to, open-source choice amongst the SWUNG community for 3D viz!

> And also I will suggest a sprint to merge `gempy` into `vtki`.

Ah, yes! A sprint would be perfect! Sprints/hackathons typically work best in-person, but since we're on different continents, perhaps we could find a few days in the coming months to organize google hangouts and formulate a plan for merging our viz efforts?

**Comment by banesullivan** [comment]
Note #159 as well

**Comment by banesullivan** [comment]
FYI: we recently had to change the name of `vtki` to `vista` per https://github.com/pyvista/vista/issues/208

**Comment by prisae** [comment]
Hi @banesullivan. I put a minimum working example on https://github.com/prisae/tmp-share/blob/master/gempy-discretize-emg3d/Example4vista.ipynb.

It is basically the Chapter 1.1 of the Tutorial, but I took out everything that is not related to the VTK plot, and added a few comments how it compares/relates to `discretize`, which might help to clarify some stuff.

All the VTK stuff in `GemPy` is located in `gempy/plot/visualization_3d.py` in the classes `vtkVisualization` and `GemPyvtkInteract`.

Running the notebook should result in this figure:

![screenshot](https://user-images.githubusercontent.com/8020943/57518215-d7e48d80-7318-11e9-96dd-07ceb3c79359.png)

Do you think something like the `mixins` in `discretize` would work in `GemPy`?

**Comment by banesullivan** [comment]
I am getting close to having PyVista streamlined enough to totally reimplement all of the VTK plotting in GemPy using PyVista with minimal code. The needed features from PyVista are:

- [x] Helpers to override keypress events (see [this](https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.add_key_event))
- [x]  easily control and manage widgets (sphere widget specifically) ref https://github.com/pyvista/pyvista/pull/383
- [ ] Subplotting with different views rather than 3 different scenes (see https://github.com/pyvista/pyvista/issues/395). In the current implementation in GemPy as well as with PyVista in its current state, three separate rendering windows are created and all simultaneously updated - this isn't desired

Once all of those are implemented, it will be super straightforward (for me at least) to reimplement the VTK code here into not much code

**Comment by Leguark** [comment]
Wow yes, thank you Bane. You are making it very easy for me! Porting GemPy to pyVista is really close in the pipeline for me too, I think latest next week I can give it a go. I am looking forward to join efforts!

Regarding to the last task. You are totally right that rendering all 4 times is an awful hack and I wonder if with the visualization tools you have already implemented if it is worth it. After 2 years having it in GemPy it is barely used. 
What I have in mind is to combine the vtk rendering with 2D sections in matplotlib embedded all in the same frame with Panel. Or having 2 renderers, the 3D and a 2D for the sections also in vtk. Any thoughts?

And regarding the sphere widgets, they are quite handy for call backs but they have way too many polygons, GemPy models with over 2k points get very slow due to the spheres. I wonder if it would not be possible to use points or some other object at least for long term.

I cannot see the day I find time to start using pyvista! It is going to be a very large quality jump!

**Comment by prisae** [comment]
Awesome @banesullivan ! PyVista+GemPy will rock!

**Comment by banesullivan** [comment]
> Porting GemPy to pyVista is really close in the pipeline for me too, I think latest next week I can give it a go. I am looking forward to join efforts!

That's really exciting, let me know how I can help!

> What I have in mind is to combine the vtk rendering with 2D sections in matplotlib embedded all in the same frame with Panel. Or having 2 renderers, the 3D and a 2D for the sections also in vtk. Any thoughts?

This is interesting... getting this up and running with Panel seems a bit challenging (only static versions of the scenes are currently supported in Panel with regards to VTK).

Having a PyQt interface with embedded 2D VTK or Matplotlib plots would be much more doable. Perhaps we could use PyVista's current sub plotting routines to have the three plots on the right show orthogonal slices through the scene. Something similar to:

Expand details for code

<details>

```py
import pyvista as pv
from pyvista import examples

mesh = examples.load_random_hills()

p = pv.Plotter(notebook=False, shape="1|3")
# Main scene
p.add_mesh(mesh)


def xcallback(normal, origin):
    p.subplot(1)
    p.add_mesh(mesh.slice(normal=normal, origin=origin), name="xslc")
    
def ycallback(normal, origin):
    p.subplot(2)
    p.add_mesh(mesh.slice(normal=normal, origin=origin), name="yslc")
    
def zcallback(normal, origin):
    p.subplot(3)
    p.add_mesh(mesh.slice(normal=normal, origin=origin), name="zslc")

p.subplot(0)
p.enable_plane_widget(xcallback, normal="x")
p.subplot(0)
p.enable_plane_widget(ycallback, normal="y")
p.subplot(0)
p.enable_plane_widget(zcallback, normal="z")

# Lock other three views in place
p.subplot(1)
p.view_yz()
p.disable()
p.subplot(2)
p.view_xz()
p.disable()
p.subplot(3)
p.view_xy()
p.disable()

p.show()
``` 

</details>

![2019-10-09 00 34 11](https://user-images.githubusercontent.com/22067021/66457065-a9d0ba00-ea2c-11e9-868e-3a7d6f254f56.gif)


> And regarding the sphere widgets, they are quite handy for call backs 

And I just streamlined the use of callbacks with sphere widgets a ton in PyVista!

> but they have way too many polygons, GemPy models with over 2k points get very slow due to the spheres. I wonder if it would not be possible to use points or some other object at least for long term.

huh. I have not experienced any performance issues using sphere widgets. Decreasing the theta/phi resolution should help out quite a bit.

**Comment by bistek** [comment]
Dear @banesullivan and @Leguark,

wow, this sounds hugely interesting! Developing this kind of interface could be a real game-changer!

May I add a couple of suggestions? They are based  on several years doing 3D modelling on large projects with commercial software...

The combination of 3D view with cross sections and map view is fundamental. What would make it really useful in full-size projects would be:

- to **detach** the cross sections from the 3D view and add **zoom and pan tools** to each window. In this way you will be able to really look into details of the model. This is fundamental if you are doing some real modelling. For instance when I model with Move, I have the 3D view open on one large screen, and I keep moving between several cross sections and the map on the other screen.

- to be able to draw **oblique** cross section, not necessarily parallel to X or Y, but oriented e.g. perpendicular to fold axes, faults, etc.. Also this is fundamental for proper structural modelling, otherwise you will always have a distorted view of your structure.

- to be able to set several **static cross sections** in key points of your structure, in addition to the interactive ones that you show above. When you have complex geological problems, having something **fixed** is very useful.

- for some applications, also **curved** cross sections are useful, for instance to correlate wells or to extract a result for some particular application.

- to be able to see **mutual intersections** between the different cross sections (e.g. a grey vertical line in section A, showing where section B crosses it, or lines in map view showing cross section locations).

- to be able to view and possibly edit the **input data** on the cross-sections. Since these data generally do not fall exactly on the cross section, this means **projecting** the data onto the sections, and showing the orientations as apparent dips. If you are interested **I have functions** for doing this according to different structural concepts. Suggestion: keep the graphics simple because in large projects you have hundreds or thousands of input data points.

- adding a **well** object with continuous and/or discrete logs, markers, etc.

- adding the possibility to **texture** surfaces (e.g. topography) with images (e.g. map or orthophoto)

- add the possibility to insert **images** in vertical cross sections (a simple way to add a geophysics background fro your interpretation).

Maybe some of these functions are already included in PyVista, which seems a very mature project. Unfortunately I am not familiar with it. Is there something in particular to read or try as a tutorial?

Thanks very much!

**Comment by bistek** [comment]
Dear @banesullivan and @Leguark, just an additional comment that came out thinking about your excellent work.

I see that you are working hard on real time updating of the model. I do not want to seem negative - this is just a suggestion - but, I am not so sure whether this feature might be really important for the end user.

This is because in real projects (with real data and a geological goal in mind) you have two important limitations:

(1) input data and model resolution are as large as possible and model computation takes time (even with my decimated test-model it takes some minutes);

(2) being able to document the changes you do to the model step-by-step is very important, and this is difficult to combine with real time editing of data etc.

Thanks for all!

**Comment by banesullivan** [comment]
@bistek, thanks so much for all of this feedback - its incredibly insightful!

I'd like to touch on your points from the first post in order as pretty much everything is currently possible with PyVista:

1. Totally doable with PyVista. A little work may be required to make the tools you describe easier to use.

2. Absolutely necessary and possible with PyVista already. You can have slices (cross-sections) at any arbitrary orientation using the `.slice()` filter or those widgets shown in my post above.

3. Implemented in PyVista via the `.slice` filter on any dataset. Simply slice a dataset and add it to the scene and it will not be interactive.

4. Again possible with PyVista at this time. However, you need to have a path to define the curve of the slice. I'm working widgets to make a spline that could define that path interactively.

5. This is possible though not straightforward to implement.

6. This is an interesting idea... Usually, I argue that an advantage of 3D viz is that you don't have to project data onto a flat plane/section, thus increasing your awareness of data proximity and uncertainty. However, you make an interesting point and I'd love to see some example using the code you mention having.

7. I'm not sure I know what you mean by a "well object" is this a class in GemPy? Either way, displaying a well with PyVista is pretty simple, so again: doable.

8. Texturing is already possible with PyVista! You just need to predefine how the texture is projected on to any surface with texture coordinates (likely exactly the same as any other software out there)

9. What exactly do you mean by images, and how would they differ from textures?

Considering just about all of these features are already possible with PyVista, we'd just need to focus on building the links between PyVista mesh types and GemPy's types

**Comment by bistek** [comment]
Hi @banesullivan . Thanks very much for your quick answer on Sunday! So I have to answer even faster. And thanks for sharing all your work that is incredibly useful for users like me!

So, I understand that first of all I need to learn something about PyVista. Can you suggest a good starting point? I've seen many tutorials but not all of them are focused on geology.

I'll come back to most points after practising a little, but I guess I can spend a few more words on the 3D -> 2D projection stuff.

The idea is this... when you have cylindrical (or almost cylindrical) geological structures, thinking and modelling in 2D is much easier and - quite often - more accurate (a cylindrical structure is one that is replicated in a very similar way along a straight axis). This is why structural geologists love cylindrical folds, and there are many other structures that can be, at least partly, considered in the same way, like when you model a fault on a cross-section containing the transport direction etc.

In 3D modelling, it could be a good idea to split (if possible) your model in "almost cylindrical" domains, and dedicate some properly oriented cross section to each domain. In some complicate situation, you could even use two different sets of cross sections in the same area, one perpendicular to fold axes and another perpendicular to faults...

OK, I guess you have an idea now, but you might still wonder what advantages you might have in cross section with respect to true 3D modelling.

The fact is that in general your input data are scattered and sparse, and they are never concentrated where you really need them (e.g. in the hinge of a fold). So if you somehow decide (e.g. with orientation statistics) that in a given volume your structure is cylindrical, you can project all your data on a cross section, and in this way your dataset will be more "rich" or "concentrated" in the 2D space where you are now doing your structural reconstruction.

Now regarding functions for projection (and some more), they are based on really easy 3D analytic geometry formulas. I have them in partly in Matlab and partly on my paper notebook, but I can translate them easily in Python functions. I just need to know some more about the way cross section planes and vectors are represented in PyVista and GemPy variables.

I can divide the useful  functions in roughly three classes:

1) functions to project point data (e.g. a set of dip measurements collected in the field or from a borehole) or line data (e.g. outcrop traces on a geological map) to a cross section, along a given vector. Basic projection is just given by the intersection of a line with a planar surface, so very easy geometry. The interesting point, from the geologist point of view, would be to be able to define the projection vector according to different structural concepts: perpendicular to cross-section, along a given vector (the same for all points in the set), or along a vector defined by some property that changes for each point (e.g. along strike of each data point).

2) functions used to intersect surfaces, including functions used to intersect 3D surfaces with a cross section plane. These are more complicated and I guess that this is more a computer graphics and 3D modelling field. The important point here is that they are very useful in many situations. For instance suppose I have a fault network model... it could be useful to find the fault lines on a cross section, and use them when modelling cylindrical folds (that are crosscut by the faults) as said above.

3) Functions to create simple geometrical primitives, such as a planar rectangular or planar surface centred at a point and with given length/height, or surfaces obtained by extruding a line along a given vector. These functions are incredibly useful when modelling sub-planar objects, like a fault network.

I attach a picture that can clarify the kind of structure I have in mind, with complex but cylindrical folds and faults.

![image](https://user-images.githubusercontent.com/12087912/66722793-2b9c5b00-ee12-11e9-9a18-3f9cc415750f.png)

I hope I have clarified somehow!

Thanks very much!

**Comment by banesullivan** [comment]
> So, I understand that first of all I need to learn something about PyVista. Can you suggest a good starting point? I've seen many tutorials but not all of them are focused on geology.

Ah, you bring up a good point... PyVsita is a general mesh analysis and visualization library so there aren't many (any) resources dedicated to showcasing it as a geo-specific tool. I've created most of the examples in PyVista's [gallery](https://docs.pyvista.org/examples/index.html) and being a geophysicist, they tend to have relevance to what we do in subsurface visualization yet I phrased everything to be as general as possible. Maybe just take a look at the examples that look interesting to you or focus on the slicing and filtering examples: https://docs.pyvista.org/examples/index.html#filtering

Also, be sure to read a little bit into the [Core API docs](https://docs.pyvista.org/core/index.html#core-api) to get a feel for the PyVista mesh types as every spatially referenced object in PyVista falls into 5 different mesh types and the rest of the library transforms/filters those mesh types or plots them in 3D. Don't get too bogged down in those docs though, that first page is likely all you need.

------

From my first pass of everything you shared above, it seems PyVista (or the VTK backend) can handle most of the tasks/projections you describe. I'll have to really dig into this when I have more time!

**Comment by bistek** [comment]
Ok, I'll study the tutorials and come back.
Thanks very much!

**Comment by banesullivan** [comment]
Back on the topic of re-implementing the view to leverage PyVista. I think we are in a state to move forward using PyVista `v0.22.4`. The side views appear to not be a huge interest so maybe we skip that feature for now? Also, this is rather complicated to implement properly so it won't come to PyVista for a while (ref https://github.com/pyvista/pyvista/issues/395)

I suppose I should start by reimplementing the `vtkVisualization` and `GemPyvtkInteract` classes? @Leguark, what would be the best approach to properly building a link between PyVista and GemPy?

It might be best to make sure there are to/from methods for converting GemPy types to PyVista types

**Comment by Leguark** [comment]
I think, this is a state that I should give it a go now. What we can do is that I develop as pull request so you can advise me if I am missing some functionality or if you would code it in a different way in vista. 

I hope to have at least 2 hours per day for this until we finish it so I will try to push it everyday for you can give me feedback. Does it make sense?

**Comment by banesullivan** [comment]
That sounds good to me and I’ll make time to help as much as I can!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Leguark** [comment]
It took its sweet time but finally pyvista is the default 3d render of GemPy! 

Still much functionality of pyvista - and the ecosystem - to take advantage of!

**Comment by prisae** [comment]
Hurray! :tada:

**Comment by banesullivan** [comment]
WOOOO!!!!!!! Awesome work you all!!

**Comment by bistek** [comment]
Hello, very good news!
Could you point us to a test notebook?
Thanks very much!

**Comment by Leguark** [comment]
we remade all the documentation with sphinx gallery too:

https://docs.gempy.org/examples/index.html#real-case-studies

(also thanks @banesullivan for the last push to convince me).

**Comment by bistek** [comment]
Thanks very much!
