### ISSUE TITLE
Create new plotting API

### ISSUE THREAD

**Issue by alexanderzimmerman** [cgre-aachen/gempy#278]
**Is your feature request related to a problem? Please describe.**
Improve the gempy plotting api.

**Describe the solution you'd like**
Versatile 2D object-oriented plotting and 3D Pyvista plotting.

**Describe alternatives you've considered**

EDIT: Here a list of features that we want/have so far and things to do. Feel free to change. This should only cover the "frontend" `plot_api.py`, there are more advanced options for experienced users in the `vista.py`. Here we should concentrate on the basic stuff. Please add anything you think belongs to the most important plotting functionality to this list:

- [x] Plotting data, lithology, scalar field in 2D sections (`plot_2d`)
- [x] Plotting data, lithology, scalar field in 3D blocks (`plot_3d`)
- [x] plot section traces for defined cross sections (
- [x] plot interactive 3D with moving cross sections (`plot_interactive_3d)
- [x] topography works in all plots
- [ ] plot gradient field (as option in 2D and 3D ?) - spin off in its own issue
- [x] Documentation!!! (#304)
- [x] add proper scales and legends to all plots
- [x] testing until release (@AlexanderJuestel, @javoha, @Leguark, etc)

**Additional context**
related to issue #156

**Comment by alexanderzimmerman** [comment]
For this week, we still need to get Travis passing in PR #301.

Moving forward, this is going to be fully supported in GemPy 2.2, which will involve changing the API docs and adding tests.

**Comment by alexanderzimmerman** [comment]
Was this closed intentionally or just automatically by closing PR #301 ? I understood that #301 merged some hidden functionality and that the API would be changed with this issue #278 . I'm re-opening for now. @Leguark , feel free to close this again if I'm mistaken.

**Comment by alexanderzimmerman** [comment]
@javoha confirmed that this issue is still open.

The work looks great so far!

What's next? @javoha , could you edit the original description of this issue so that the goals are more clear? Do we have anything like a _definition of done_? Right now the scope of this issue is much larger than it probably needs to be.

**Comment by Leguark** [comment]
This epic should stop until we fix fundamental bugs that the core of the vista class has created. For now I just (manually) reverted the class to the state it was pre-merged

**Comment by javoha** [comment]
Can you specify which bugs you mean?

**Comment by Leguark** [comment]
It is fundamental stuff in order to update the model as surfaces and other parameters are added or shuffled around. At the moment I kept alex version as _Vista and restore my old implementation as Vista, and the api imports: import _Vista as Vista. 

In short, everything still work as it did but I prefer to stop adding features until the core is more robust in order to reduce the amount of code we need to update
